### ISSUE TITLE
geomtery error on web builds

### ISSUE THREAD

**Issue by fisforfaheem** [cmdrootaccess/another-flushbar#105] opened 2023-05-09 13:01 UTC
<img width="789" alt="image" src="https://github.com/cmdrootaccess/another-flushbar/assets/35878088/8bfd40ab-3eb2-46e6-9c33-3b80c9a3ed7b">

**Comment by cmdrootaccess** [comment] 2023-05-09 13:06
this is only happening web builds ?

**Comment by fisforfaheem** [comment] 2023-05-09 13:09
yes, i am tired of finding issues for last 6 hours, no help found on web

**Comment by cmdrootaccess** [comment] 2023-05-09 13:09
okay give me a few minutes let me run on web

**Comment by fisforfaheem** [comment] 2023-05-09 13:11
ok

**Comment by cmdrootaccess** [comment] 2023-05-09 13:22
i just run in the web right now. and no issues
https://github.com/cmdrootaccess/another-flushbar/assets/14039016/e9789cea-affc-41f7-bc72-b52a28d6b6b7

**Comment by cmdrootaccess** [comment] 2023-05-09 13:25
https://github.com/cmdrootaccess/another-flushbar/assets/14039016/9a33c64f-55e8-457c-b19a-ee087390ab9b

**Comment by cmdrootaccess** [comment] 2023-05-09 15:10
closing as flushbar is not the root cause of this error

**Closed by cmdrootaccess** 2023-05-09 15:10 UTC

**Comment by fisforfaheem** [comment] 2023-05-09 15:16
Sie can u please at least give update to pub. Dev🪃, its been 8 months,
please bump sdk etx

**Comment by fisforfaheem** [comment] 2023-05-09 15:30
Flutter 3.7 but planning to shift to flutter beta soon

**Comment by cmdrootaccess** [comment] 2023-05-09 15:34
am also using the same version. i guess the issue is with some of your dependencies .

<img width="553" alt="Screen Shot 2023-05-09 at 6 33 25 PM" src="https://github.com/cmdrootaccess/another-flushbar/assets/14039016/f8f53ef0-5c6d-4390-a6ef-6445d2d6924d">

**Comment by cmdrootaccess** [comment] 2023-05-09 15:52
sure i will do that

**Comment by cmdrootaccess** [comment] 2023-05-09 19:49
solved in https://github.com/cmdrootaccess/another-flushbar/issues/106
